application: laser-top
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /add
  script: main.app
  login: admin

- url: /editCommand
  script: main.app
  login: admin

- url: /achievements
  script: achievements.app
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest