application: lasertag
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
- url: /stylesheets
  static_dir: stylesheets

libraries:
- name: jinja2
  version: latest