application: laser-top
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(add|editCommand|addCommand)
  script: main.app
  login: admin

- url: /achievements/(recalculate|initialization)
  script: main.app
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest